services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODE: prod
    ports:
      - "3000:${PORT:-3000}"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always
