services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:${PORT}"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always
